'use client'
import {createContext,useContext,useEffect,useMemo,useState} from 'react'
import {Activity,BarChart3,Bell,Check,ChevronDown,ChevronLeft,ChevronRight,ClipboardCheck,FileText,FlaskConical,Globe,Grid2X2,HelpCircle,Layers3,LockKeyhole,Menu,Search,Settings,Shield,ShieldAlert,ShieldCheck,X} from 'lucide-react'
import {useLocale,useTranslations} from 'next-intl'
import {usePathname,useRouter} from '@/i18n/routing'
import {organizations,systems,findings,controls,requirements,evidence} from '@/data/demo'
import type {Locale} from '@/domain/models'
type ThemePreference='light'|'dark'|'system'
type WorkspaceContextValue={organizationId:string;setOrganizationId:(id:string)=>void;theme:ThemePreference;setTheme:(theme:ThemePreference)=>void}
const WorkspaceContext=createContext<WorkspaceContextValue|null>(null)
export function useWorkspace(){const value=useContext(WorkspaceContext);if(!value)throw new Error('Workspace context is unavailable');return value}
const nav=[{group:'workspace',items:[['overview','Overview',Grid2X2],['systems','AI systems',Layers3],['evaluations','Evaluations',FlaskConical],['findings','Findings',ShieldAlert],['monitoring','Monitoring',Activity],['release','Release gates',LockKeyhole]]},{group:'assurance',items:[['controls','Controls',ClipboardCheck],['compliance','Compliance',Shield],['evidence','Evidence',FileText],['reports','Reports',BarChart3]]},{group:'admin',items:[['integrations','Integrations',Globe],['settings','Settings',Settings]]}] as const
export function WorkspaceShell({children}:{children:React.ReactNode}){
 const t=useTranslations();const navT=useTranslations('nav');const roleT=useTranslations('roles');const path=usePathname();const router=useRouter();const locale=useLocale() as Locale
 const [organizationId,setOrganizationId]=useState('org-health');const [organizationReady,setOrganizationReady]=useState(false);const [theme,setTheme]=useState<ThemePreference>('system');const [themeReady,setThemeReady]=useState(false);const [systemTheme,setSystemTheme]=useState<'light'|'dark'>('light');const [collapsed,setCollapsed]=useState(false);const [orgOpen,setOrgOpen]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [query,setQuery]=useState('');const [toast,setToast]=useState('')
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setSearchOpen(true)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 useEffect(()=>{const media=window.matchMedia('(prefers-color-scheme: dark)');const update=()=>setSystemTheme(media.matches?'dark':'light');update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[])
 useEffect(()=>{const stored=window.localStorage.getItem('iaa-v1:active-org');if(organizations.some(item=>item.id===stored))setOrganizationId(stored!);setOrganizationReady(true)},[])
 useEffect(()=>{if(organizationReady)window.localStorage.setItem('iaa-v1:active-org',organizationId)},[organizationId,organizationReady])
 useEffect(()=>{const stored=window.localStorage.getItem('iaa-v1:theme');if(stored==='light'||stored==='dark'||stored==='system')setTheme(stored);setThemeReady(true)},[])
 useEffect(()=>{if(themeReady)window.localStorage.setItem('iaa-v1:theme',theme)},[theme,themeReady])
 const resolvedTheme=theme==='system'?systemTheme:theme
 useEffect(()=>{document.documentElement.dataset.theme=resolvedTheme},[resolvedTheme])
 const org=organizations.find(item=>item.id===organizationId)!
 const scopedSystems=systems.filter(system=>system.organizationId===organizationId);const scopedFindings=findings.filter(finding=>finding.organizationId===organizationId);const scopedEvidence=evidence.filter(item=>item.organizationId===organizationId)
 const searchResults=useMemo(()=>{const q=query.toLowerCase();return [...scopedSystems.filter(item=>`${item.name} ${item.owner}`.toLowerCase().includes(q)).map(item=>({label:item.name,detail:item.id,url:`/${locale}/systems?system=${item.id}`})),...scopedFindings.filter(item=>`${item.title} ${item.id}`.toLowerCase().includes(q)).map(item=>({label:item.title,detail:item.id,url:`/${locale}/findings?finding=${item.id}`})),...controls.filter(item=>`${item.title} ${item.id}`.toLowerCase().includes(q)).map(item=>({label:item.title,detail:item.id,url:`/${locale}/controls?control=${item.id}`})),...requirements.filter(item=>item.title.toLowerCase().includes(q)).map(item=>({label:item.title,detail:t('ui.frameworkRequirement'),url:`/${locale}/compliance`})),...scopedEvidence.filter(item=>item.title.toLowerCase().includes(q)).map(item=>({label:item.title,detail:item.id,url:`/${locale}/evidence?evidence=${item.id}`}))]},[query,scopedSystems,scopedFindings,scopedEvidence,locale,t])
 const current=path.split('/').filter(Boolean).join(' / ');const avatar=organizationId==='org-health'?'DH':organizationId==='org-bank'?'EB':'EC'
 return <WorkspaceContext.Provider value={{organizationId,setOrganizationId,theme,setTheme}}><div className={`app ${resolvedTheme==='dark'?'dark':''}`}><aside className={`sidebar ${collapsed?'collapsed':''}`}><div className="brand"><div className="brandmark"><ShieldCheck size={19}/></div>{!collapsed&&<div className="brandtext"><b>Independent</b><span>AI Assurance</span></div>}<button className="icon-btn collapse" aria-label={t('ui.collapseSidebar')} onClick={()=>setCollapsed(!collapsed)}><ChevronLeft size={16}/></button></div>
 <button className="org-switch" aria-expanded={orgOpen} onClick={()=>setOrgOpen(!orgOpen)}><span className="org-avatar">{avatar}</span>{!collapsed&&<><span className="org-name">{org.name}</span><ChevronDown size={14}/></>}</button>{orgOpen&&!collapsed&&<div className="org-menu">{organizations.map(item=><button key={item.id} onClick={()=>{setOrganizationId(item.id);setOrgOpen(false);setToast(t('ui.workspaceSwitched',{name:item.name}))}}>{item.name}{item.id===organizationId&&<Check size={14}/>}</button>)}</div>}
 <div className="nav-scroll">{nav.map(group=><section className="nav-group" key={group.group}><div className="nav-label">{!collapsed&&navT(group.group)}</div>{group.items.map(([id,,Icon])=><a key={id} className={`nav-item ${current.startsWith(id)?'active':''}`} href={`/${locale}/${id}`} title={collapsed?navT(id):undefined}><Icon size={16}/>{!collapsed&&<span>{navT(id)}</span>}{id==='findings'&&!collapsed&&scopedFindings.length>0&&<small className="nav-count">{scopedFindings.length}</small>}</a>)}</section>)}<div className="nav-label framework-nav-label">{!collapsed&&navT('frameworks')}</div>{!collapsed&&['EU AI Act','ISO/IEC 42001','NIST AI RMF'].map(name=><a className="framework-link" key={name} href={`/${locale}/compliance`}><span className="framework-dot"/>{name}</a>)}</div>
 <div className="sidebar-bottom"><button className="help-row" onClick={()=>router.push('/'+locale+'/overview#methodology' as never)}><HelpCircle size={16}/>{!collapsed&&t('common.help')}</button><div className="user-row"><div className="user-avatar">AM</div>{!collapsed&&<div className="user-copy"><b>Alex Morgan</b><span>{roleT('GOVERNANCE_MANAGER')}</span></div>}</div></div></aside>
 <main className="main"><header className="topbar"><button className="mobile-menu icon-btn" aria-label={t('ui.toggleMenu')} onClick={()=>setCollapsed(!collapsed)}><Menu size={18}/></button><div className="breadcrumb"><span>{org.name}</span><ChevronRight size={14}/><b>{navT((current.split('/')[0]||'overview') as never)}</b></div><div className="top-actions"><button className="search-trigger" onClick={()=>setSearchOpen(true)}><Search size={15}/><span>{t('common.search')}</span><kbd>⌘ K</kbd></button><select className="locale-btn" value={locale} aria-label={t('settings.language')} onChange={event=>router.replace(path,{locale:event.target.value as Locale})}><option value="en">EN</option><option value="de">DE</option><option value="tr">TR</option></select><select className="theme-select" value={theme} aria-label={t('settings.appearance')} onChange={event=>setTheme(event.target.value as ThemePreference)}><option value="light">{t('settings.light')}</option><option value="dark">{t('settings.dark')}</option><option value="system">{t('settings.system')}</option></select><button className="icon-btn notification" aria-label={t('ui.notifications')} onClick={()=>setToast(t('ui.noNotifications'))}><Bell size={17}/></button><div className="top-avatar">AM</div></div></header><div className="content">{children}</div><footer><span>{t('common.position')}</span><span>{t('ui.methodologyVersion')} · {t('common.demo')}</span></footer></main>
 {searchOpen&&<div className="modal-scrim" onClick={()=>setSearchOpen(false)}><section className="search-modal" role="dialog" aria-modal="true" aria-label={t('common.search')} onClick={event=>event.stopPropagation()}><div className="modal-search"><Search size={18}/><input autoFocus placeholder={t('common.search')} value={query} onChange={event=>setQuery(event.target.value)}/><button aria-label={t('common.close')} onClick={()=>setSearchOpen(false)}><X size={17}/></button></div><div className="search-results">{searchResults.slice(0,12).map((result,index)=><a href={result.url} key={`${result.detail}-${index}`}><span>{result.label}</span><small>{result.detail}</small></a>)}</div></section></div>}{toast&&<button className="toast" onClick={()=>setToast('')}><Check size={16}/>{toast}</button>}</div></WorkspaceContext.Provider>
}
