'use client'
import {useEffect,useMemo,useState} from 'react'
import {useTranslations} from 'next-intl'
import {ArrowRight,ClipboardList,Search} from 'lucide-react'
import {useWorkspace} from '@/components/shell/WorkspaceShell'
import {PageHeading,StatusPill,EmptyState} from '@/components/assurance/shared'
import {results,testCases,controls,mappings,requirements,frameworks,evidence,session} from '@/data/demo'
import {workflowRepository} from '@/repositories/workflow'
import {hasPermission} from '@/lib/permissions'
import {Link} from '@/i18n/routing'
import type {Finding} from '@/domain/models'
import type {FindingStatus} from '@/services/findings'
export function Findings(){const t=useTranslations();const {organizationId}=useWorkspace();const [items,setItems]=useState(()=>workflowRepository.findings(organizationId));const [query,setQuery]=useState('');const [filter,setFilter]=useState('ALL');const [selected,setSelected]=useState('');useEffect(()=>setItems(workflowRepository.findings(organizationId)),[organizationId]);useEffect(()=>{const id=new URLSearchParams(window.location.search).get('finding');if(id&&items.some(f=>f.id===id))setSelected(id)},[items]);const current=items.find(f=>f.id===selected);const filtered=useMemo(()=>items.filter(f=>(filter==='ALL'||f.status===filter)&&`${f.title} ${f.id} ${f.owner} ${f.controlId}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);const update=(f:Finding,status:FindingStatus)=>{if(!hasPermission(session.role,'finding:manage'))return;const next=workflowRepository.updateFinding(f.id,status,session.name,`Status changed to ${status}`);setItems(next.filter(x=>x.organizationId===organizationId))};return <><PageHeading namespace="findings" titleKey="title" subtitleKey="subtitle"/>{current?<FindingDetail finding={current} onBack={()=>setSelected('')}/>:<section className="panel listing-panel"><div className="list-toolbar"><div className="input-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('findings.search')}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">{t('common.all')}</option>{['OPEN','INVESTIGATING','IN_REMEDIATION','READY_FOR_RETEST','RESOLVED','RISK_ACCEPTED'].map(x=><option key={x}>{x}</option>)}</select></div>{filtered.length?<div className="table-wrap"><table><thead><tr><th>FINDING</th><th>{t('common.system')}</th><th>{t('findings.severity')}</th><th>{t('common.owner')}</th><th>{t('findings.due')}</th><th>{t('common.status')}</th><th>ACTION</th></tr></thead><tbody>{filtered.map(f=><tr key={f.id} className="click-row" onClick={()=>setSelected(f.id)}><td>{f.title}<small>{f.id}</small></td><td>{f.systemId}</td><td><StatusPill status={f.severity}/></td><td>{f.owner}</td><td>{f.dueDate}</td><td>{f.status}</td><td><button type="button" className="small-action" onClick={e=>{e.stopPropagation();update(f,f.status==='OPEN'?'INVESTIGATING':'RESOLVED')}}>{f.status==='OPEN'?t('findings.investigate'):t('findings.resolve')}</button></td></tr>)}</tbody></table></div>:<EmptyState>No findings match this organization and filter.</EmptyState>}</section>}</>}
function FindingDetail({finding:f,onBack}:{finding:Finding;onBack:()=>void}){const t=useTranslations();const test=results.find(r=>r.id===f.testResultId);const tc=testCases.find(x=>x.id===test?.testCaseId);const control=controls.find(c=>c.id===f.controlId);const refs=mappings.filter(m=>m.masterControlId===f.controlId);const linkedEvidence=evidence.filter(e=>f.evidenceIds.includes(e.id));return <><button className="text-action" onClick={onBack}>← {t('findings.title')}</button><section className="panel finding-detail-top"><span className="severity-large"><AlertTriangle/></span><div><StatusPill status={f.severity}/><h2>{f.title}</h2><p>{f.id} · {f.systemId} · {f.owner} · Due {f.dueDate}</p></div></section><div className="dashboard-grid"><section className="panel"><h2>{t('findings.trace')}</h2><Trace title="Finding" detail={`${f.id} · ${f.status}`}/><Trace title="Test Result" detail={`${test?.id} · ${test?.result} · confidence ${test?.confidence}`}/><Trace title="Test Case" detail={`${tc?.id} · ${tc?.title}`}/><Trace title="Evaluation Procedure" detail={`${control?.activeVersionId} · ${control?.automationCapability}`}/><Trace title="Master Control" detail={`${control?.id} · ${control?.title}`}/>{refs.map(m=>{const requirement=requirements.find(r=>r.id===m.frameworkRequirementId);const framework=frameworks.flatMap(x=>x.versions).find(v=>v.id===m.frameworkVersionId);return <Trace key={m.id} title={`${framework?.frameworkId} ${framework?.version}`} detail={`${requirement?.id} · ${requirement?.title} · ${m.relationship} · ${m.validationStatus}`}/>})}<Trace title="Evidence" detail={linkedEvidence.map(e=>`${e.id} ${e.quality}`).join(', ')||'No linked evidence'}/></section><section className="panel"><h2>{t('findings.history')}</h2>{f.history.map(h=><p key={h.id}><b>{h.status}</b> · {h.actor} · {h.timestamp}<small>{h.reason}</small></p>)}<div className="finding-actions">{['INVESTIGATING','IN_REMEDIATION','READY_FOR_RETEST','RESOLVED','RISK_ACCEPTED'].map(x=><button className="small-action" key={x} onClick={()=>{workflowRepository.updateFinding(f.id,x as FindingStatus,session.name,`Reviewer selected ${x}`);window.location.reload()}}>{x.replaceAll('_',' ')}</button>)}</div><Link href="/release">Review release gate <ArrowRight size={14}/></Link></section></div><section className="panel"><h2>Observed behavior</h2><p>{test?.expectedBehavior}</p><p>{test?.observedBehavior}</p><p>{test?.notes}</p><h3>Evidence artifacts</h3>{linkedEvidence.map(e=><p key={e.id}><ClipboardList size={14}/> {e.id} · {e.title} · {e.quality} · <a href={e.reference.uri}>{e.reference.kind}</a></p>)}<button className="btn outline" onClick={()=>{workflowRepository.updateFinding(f.id,'RISK_ACCEPTED',session.name,'Demo risk acceptance requires a proper expiry and approval record.');window.location.reload()}}>{t('findings.accept')}</button></section></>}
function AlertTriangle(){return <span aria-hidden="true">!</span>}
function Trace({title,detail}:{title:string;detail:string}){return <div className="trace-row"><b>{title}</b><span>{detail}</span></div>}
