'use client'
import {useEffect,useMemo,useState} from 'react'
import {useTranslations} from 'next-intl'
import {ArrowRight,ClipboardList,Search} from 'lucide-react'
import {useWorkspace} from '@/components/shell/workspace-context'
import {PageHeading,StatusPill,EmptyState} from '@/components/assurance/shared'
import {results,testCases,controls,mappings,requirements,frameworks,evidence,session} from '@/data/demo'
import {workflowRepository} from '@/repositories/workflow'
import {hasPermission} from '@/lib/permissions'
import {Link} from '@/i18n/routing'
import type {Finding} from '@/domain/models'
import type {FindingStatus} from '@/services/findings'
export function Findings(){const t=useTranslations();const {organizationId}=useWorkspace();const [items,setItems]=useState(()=>workflowRepository.findings(organizationId));const [query,setQuery]=useState('');const [filter,setFilter]=useState('ALL');const [selected,setSelected]=useState('');const [error,setError]=useState('');useEffect(()=>setItems(workflowRepository.findings(organizationId)),[organizationId]);useEffect(()=>{const id=new URLSearchParams(window.location.search).get('finding');if(id&&items.some(f=>f.id===id))setSelected(id)},[items]);const current=items.find(f=>f.id===selected);const filtered=useMemo(()=>items.filter(f=>(filter==='ALL'||f.status===filter)&&`${f.title} ${f.id} ${f.owner} ${f.controlId}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);const update=(f:Finding,status:FindingStatus)=>{if(!hasPermission(session.role,'finding:manage')){setError(t('ui.permissionDenied'));return}const next=workflowRepository.updateFinding(f.id,status,session.name,t('ui.statusChanged',{status:t(`statuses.${status}`)}));setItems(next.filter(x=>x.organizationId===organizationId));setError('')};return <><PageHeading namespace="findings" titleKey="title" subtitleKey="subtitle"/>{current?<FindingDetail finding={current} onBack={()=>setSelected('')} onUpdate={update}/>:<section className="panel listing-panel"><div className="list-toolbar"><div className="input-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('findings.search')}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">{t('common.all')}</option>{['OPEN','INVESTIGATING','IN_REMEDIATION','READY_FOR_RETEST','RESOLVED','RISK_ACCEPTED'].map(x=><option key={x} value={x}>{t(`statuses.${x}`)}</option>)}</select></div>{error&&<p role="alert">{error}</p>}{filtered.length?<div className="table-wrap"><table><thead><tr><th>{t('ui.findingHeader')}</th><th>{t('common.system')}</th><th>{t('findings.severity')}</th><th>{t('common.owner')}</th><th>{t('findings.due')}</th><th>{t('common.status')}</th><th>{t('ui.actions')}</th></tr></thead><tbody>{filtered.map(f=><tr key={f.id} className="click-row" onClick={()=>setSelected(f.id)}><td>{f.title}<small>{f.id}</small></td><td>{f.systemId}</td><td><StatusPill status={f.severity}/></td><td>{f.owner}</td><td>{f.dueDate}</td><td><StatusPill status={f.status}/></td><td><button type="button" className="small-action" onClick={e=>{e.stopPropagation();update(f,f.status==='OPEN'?'INVESTIGATING':'RESOLVED')}}>{f.status==='OPEN'?t('findings.investigate'):t('findings.resolve')}</button></td></tr>)}</tbody></table></div>:<EmptyState>{t('ui.emptyFindingFilter')}</EmptyState>}</section>}</>}
function FindingDetail({finding:f,onBack,onUpdate}:{finding:Finding;onBack:()=>void;onUpdate:(finding:Finding,status:FindingStatus)=>void}){const t=useTranslations();const test=results.find(r=>r.id===f.testResultId);const tc=testCases.find(x=>x.id===test?.testCaseId);const control=controls.find(c=>c.id===f.controlId);const refs=mappings.filter(m=>m.masterControlId===f.controlId);const linkedEvidence=evidence.filter(e=>f.evidenceIds.includes(e.id));return <><button className="text-action" onClick={onBack}>← {t('findings.title')}</button><section className="panel finding-detail-top"><span className="severity-large" aria-hidden="true">!</span><div><StatusPill status={f.severity}/><h2>{f.title}</h2><p>{f.id} · {f.systemId} · {f.owner} · {t('ui.due')}: {f.dueDate}</p></div></section><div className="dashboard-grid"><section className="panel"><h2>{t('findings.trace')}</h2><Trace title={t('ui.findingHeader')} detail={`${f.id} · ${t(`statuses.${f.status}`)}`}/><Trace title={t('ui.testResult')} detail={`${test?.id} · ${test?t(`statuses.${test.result}`):''} · ${t('ui.confidence')} ${test?.confidence}`}/><Trace title={t('ui.testCase')} detail={`${tc?.id} · ${tc?.title}`}/><Trace title={t('ui.evaluationProcedure')} detail={`${control?.activeVersionId} · ${control?.automationCapability}`}/><Trace title={t('ui.masterControl')} detail={`${control?.id} · ${control?.title}`}/>{refs.map(m=>{const requirement=requirements.find(r=>r.id===m.frameworkRequirementId);const framework=frameworks.flatMap(x=>x.versions).find(v=>v.id===m.frameworkVersionId);return <Trace key={m.id} title={`${framework?.frameworkId} ${framework?.version}`} detail={`${requirement?.id} · ${requirement?.title} · ${t(`statuses.${m.relationship}`)} · ${t(`statuses.${m.validationStatus}`)}`}/>})}<Trace title={t('common.evidence')} detail={linkedEvidence.map(e=>`${e.id} ${t(`statuses.${e.quality}`)}`).join(', ')||t('ui.noLinkedEvidence')}/></section><section className="panel"><h2>{t('findings.history')}</h2>{f.history.map(h=><p key={h.id}><b><StatusPill status={h.status}/></b> · {h.actor} · {h.timestamp}<small>{h.reason}</small></p>)}<div className="finding-actions">{['INVESTIGATING','IN_REMEDIATION','READY_FOR_RETEST','RESOLVED','RISK_ACCEPTED'].map(x=><button className="small-action" key={x} onClick={()=>onUpdate(f,x as FindingStatus)}>{t(`statuses.${x}`)}</button>)}</div><Link href="/release">{t('ui.reviewGate')} <ArrowRight size={14}/></Link></section></div><section className="panel"><h2>{t('ui.observedBehavior')}</h2><p>{test?.expectedBehavior}</p><p>{test?.observedBehavior}</p><p>{test?.notes}</p><h3>{t('ui.evidenceArtifacts')}</h3>{linkedEvidence.map(e=><p key={e.id}><ClipboardList size={14}/> {e.id} · {e.title} · {t(`statuses.${e.quality}`)} · <a href={e.reference.uri}>{t(`statuses.${e.reference.kind}`)}</a></p>)}<button className="btn outline" onClick={()=>onUpdate(f,'RISK_ACCEPTED')}>{t('findings.accept')}</button></section></>}
function Trace({title,detail}:{title:string;detail:string}){return <div className="trace-row"><b>{title}</b><span>{detail}</span></div>}
