import {describe,expect,it} from 'vitest'
import {assuranceScore} from '../src/lib/scoring'
import {frameworkCoverage} from '../src/lib/coverage'
import {controlAppliesToSystem} from '../src/lib/coverage/applicability'
import {confidenceScore} from '../src/lib/confidence'
import {assessSystemRisk} from '../src/lib/risk'
import {evaluateMetric} from '../src/services/monitoring'
import {evaluateReleaseGate} from '../src/services/release'
import {runEvaluation,evaluationInputSchema,cancelEvaluation} from '../src/services/evaluation'
import {transitionFinding} from '../src/services/findings'
import {hasPermission} from '../src/lib/permissions'
import {systems,frameworks,requirements,controls,mappings,procedures,evidenceRequirements,evaluations,results,testCases,evidence,findings,metrics,evaluator,releasePolicy} from '../src/data/demo'
import en from '../src/messages/en.json'
import de from '../src/messages/de.json'
import tr from '../src/messages/tr.json'

const flatten=(obj:Record<string,unknown>,prefix=''):string[]=>Object.entries(obj).flatMap(([key,value])=>typeof value==='object'&&value!==null?flatten(value as Record<string,unknown>,prefix?`${prefix}.${key}`:key):[prefix?`${prefix}.${key}`:key])
const findValue=(obj:Record<string,unknown>,path:string)=>path.split('.').reduce((value,key)=>(value as Record<string,unknown>)[key],obj as unknown)

describe('assurance architecture and calculations',()=>{
 it('calculates score deterministically from test results, findings and evidence',()=>{expect(assuranceScore(results,findings)).toEqual(assuranceScore(results,findings));expect(assuranceScore(results,findings).score).toBeLessThan(100)})
 it('recalculates score when a control result changes',()=>{const before=assuranceScore(results,findings).score;const after=assuranceScore(results.map(r=>r.id==='R-HALL-01'?{...r,result:'PASS' as const}:r),findings).score;expect(after).toBeGreaterThan(before)})
 it('computes framework coverage only from explicit mapped and assessed controls',()=>{const f=frameworks[0];const result=frameworkCoverage(f,requirements,mappings,controls,results);expect(result.mappings.every(m=>m.frameworkVersionId===f.activeVersionId)).toBe(true);expect(result.coverage).toBe(Math.round(result.assessedControls/result.mappedControls*100))})
 it('changes coverage when the set of assessed controls changes',()=>{const f=frameworks[0];const full=frameworkCoverage(f,requirements,mappings,controls,results);const reduced=frameworkCoverage(f,requirements,mappings,controls,results.filter(r=>r.id!=='R-HALL-01'));expect(reduced.coverage).toBeLessThan(full.coverage)})
 it('calculates confidence separately from risk',()=>{const confidence=confidenceScore(results,evaluator,Object.fromEntries(evidence.map(e=>[e.id,e.quality])),5,.95);const risk=assessSystemRisk(systems[0]);expect(confidence.score).toBeGreaterThan(0);expect(confidence.label).toContain('HIGH');expect(risk.residualRisk).not.toBe(100-confidence.score)})
 it('derives confidence evidence quality and freshness from explicit factors',()=>{const fresh=confidenceScore(results,evaluator,Object.fromEntries(evidence.map(e=>[e.id,e.quality])),1,.95);const stale=confidenceScore(results,evaluator,Object.fromEntries(evidence.map(e=>[e.id,e.quality])),120,.5);expect(fresh.score).toBeGreaterThan(stale.score)})
 it('computes risk from context and risk inputs, not assurance score',()=>{const risk=assessSystemRisk(systems[0]);expect(risk.likelihood).toBe(4);expect(risk.impact).toBe(5);expect(risk.exposure).toBeGreaterThan(0);expect(risk.residualRisk).toBeGreaterThan(0)})
 it('preserves framework version identifiers in historical evaluations',()=>{expect(evaluations[0].frameworkVersionIds).toContain(frameworks[0].activeVersionId);expect(evaluations[0].controlVersionIds).toContain(controls[0].activeVersionId)})
 it('keeps framework mappings referentially valid and does not infer mappings by position',()=>{expect(mappings.length).toBeGreaterThan(0);for(const m of mappings){expect(frameworks.flatMap(f=>f.versions).some(v=>v.id===m.frameworkVersionId)).toBe(true);expect(requirements.some(r=>r.id===m.frameworkRequirementId)).toBe(true);expect(controls.some(c=>c.id===m.masterControlId)).toBe(true)}})
 it('does not apply LLM security controls to classification systems',()=>{const bank=systems.find(s=>s.id==='SYS-BANK')!;expect(controlAppliesToSystem(controls.find(c=>c.id==='SEC-LLM-001')!,bank)).toBe(false);expect(controlAppliesToSystem(controls.find(c=>c.id==='HUM-OVS-001')!,bank)).toBe(true)})
 it('detects the seeded 1.8% to 4.7% hallucination regression',()=>{const m=metrics.find(x=>x.id==='M-HALL')!;expect(evaluateMetric(m).delta).toBeCloseTo(2.9);expect(evaluateMetric(m).status).toBe('REGRESSION_DETECTED')})
 it('does not signal regression below the 1 percentage point threshold',()=>{const m=metrics.find(x=>x.id==='M-HALL')!;expect(evaluateMetric({...m,current:2.7}).status).toBe('NORMAL')})
 it('recalculates release decisions from current regression and finding states',()=>{const hc=systems[0];const blocked=evaluateReleaseGate(hc.organizationId,hc.id,hc.activeVersionId,releasePolicy,findings,metrics.map(evaluateMetric),results,undefined,evaluations);const clear=evaluateReleaseGate(hc.organizationId,hc.id,hc.activeVersionId,releasePolicy,findings.map(f=>({...f,status:'RESOLVED'})),metrics.map(m=>evaluateMetric({...m,status:'NORMAL',current:m.baseline})),results,undefined,evaluations);expect(blocked.decision).toBe('BLOCKED');expect(clear.decision).toBe('REVIEW_REQUIRED')})
 it('requires role permission for release override',()=>{expect(hasPermission('GOVERNANCE_MANAGER','release:approve')).toBe(true);expect(hasPermission('VIEWER','release:approve')).toBe(false)})
 it('validates evaluation configuration and test suite selection',()=>{expect(evaluationInputSchema.safeParse({organizationId:'org-health',systemId:'SYS-HCP',systemVersionId:'hcp-v38',profileId:'Regression',suiteIds:['suite-gen'],scope:'Version compare'}).success).toBe(true);expect(evaluationInputSchema.safeParse({organizationId:'org-health',systemId:'',systemVersionId:'',profileId:'',suiteIds:[],scope:''}).success).toBe(false)})
 it('runs a seeded evaluation with a complete lifecycle and stable results',async()=>{const states:string[]=[];const input={organizationId:'org-health',systemId:'SYS-HCP',systemVersionId:'hcp-v38',profileId:'Regression',suiteIds:['suite-gen','suite-sec'],scope:'Compare versions'};const run=await runEvaluation(input,x=>states.push(x.status));expect(states).toEqual(['QUEUED','RUNNING','COMPLETED']);expect(run.evaluation.configurationSnapshot.externalModelContact).toBe('false');expect(run.results.map(r=>r.result)).toEqual(['FAIL','FAIL'])})
 it('supports evaluation cancellation as a lifecycle transition',()=>{expect(cancelEvaluation('RUNNING')).toBe('CANCELLED');expect(cancelEvaluation('COMPLETED')).toBe('COMPLETED')})
 it('records finding transitions with structured audit state',()=>{const finding=findings[0];const change=transitionFinding(finding,'INVESTIGATING','Auditor','Assigned for review','2026-09-25T09:00:00Z');expect(change.finding.history.at(-1)?.status).toBe('INVESTIGATING');expect(change.audit).toMatchObject({organizationId:finding.organizationId,objectType:'Finding',objectId:finding.id,previousState:'OPEN',newState:'INVESTIGATING'})})
 it('rejects unsupported finding transitions and requires a reason',()=>{expect(()=>transitionFinding(findings[0],'RESOLVED','Auditor','skip')).toThrow();expect(()=>transitionFinding(findings[0],'INVESTIGATING','Auditor','')).toThrow()})
 it('keeps organization records isolated',()=>{expect(systems.filter(s=>s.organizationId==='org-bank').map(s=>s.id)).toEqual(['SYS-BANK']);expect(findings.filter(f=>f.organizationId==='org-bank').every(f=>f.systemId==='SYS-BANK')).toBe(true);expect(evidence.filter(e=>e.organizationId==='org-bank').every(e=>e.systemId==='SYS-BANK')).toBe(true)})
 it('keeps evidence quality tied to result references',()=>{expect(evidence.every(e=>results.some(r=>r.id===e.testResultId&&r.evidenceIds.includes(e.id)))).toBe(true);expect(new Set(evidence.map(e=>e.quality)).size).toBeGreaterThan(0)})
 it('completes the primary finding to framework version and evidence chain',()=>{const finding=findings[0];const result=results.find(r=>r.id===finding.testResultId)!;const test=testCases.find(t=>t.id===result.testCaseId)!;const procedure=procedures.find(p=>p.controlVersionId===controls.find(c=>c.id===test.controlId)?.activeVersionId)!;const control=controls.find(c=>c.id===procedure.controlVersionId.split('-v')[0])??controls.find(c=>c.id===finding.controlId)!;const mapping=mappings.find(m=>m.masterControlId===control.id)!;const requirement=requirements.find(r=>r.id===mapping.frameworkRequirementId)!;const version=frameworks.flatMap(f=>f.versions).find(v=>v.id===requirement.frameworkVersionId)!;expect(evidenceRequirements.some(e=>e.controlVersionId===procedure.controlVersionId)).toBe(true);expect(version.frameworkId).toBeTruthy();expect(evidence.some(e=>finding.evidenceIds.includes(e.id))).toBe(true)})
 it('keeps control framework mapping output sourced from mapping records',()=>{const eu=frameworks[0];const visible=frameworkCoverage(eu,requirements,mappings,controls,results).mappings;expect(visible).toEqual(mappings.filter(m=>m.frameworkVersionId===eu.activeVersionId));expect(visible.length).toBeGreaterThan(0)})
 it('contains all English UI message keys in German and Turkish',()=>{const keys=flatten(en);expect(flatten(de)).toEqual(expect.arrayContaining(keys));expect(flatten(tr)).toEqual(expect.arrayContaining(keys));for(const key of keys){expect(typeof findValue(de,key)).toBe('string');expect(typeof findValue(tr,key)).toBe('string')}})
 it('reconciles primary scenario values and release gate seed data',()=>{expect(metrics.find(m=>m.id==='M-HALL')).toMatchObject({baseline:1.8,current:4.7,threshold:1});expect(metrics.find(m=>m.id==='M-INJ')).toMatchObject({baseline:96,current:93});expect(metrics.find(m=>m.id==='M-FAIR')).toMatchObject({baseline:77,current:72});expect(results.find(r=>r.id==='R-PII-01')?.result).toBe('PASS');expect(releasePolicy.organizationId).toBe('org-health')})
 it('uses actual versioned framework requirement and control mapping identifiers',()=>{expect(frameworks.length).toBeGreaterThanOrEqual(7);expect(frameworks.some(f=>f.id==='ISO_42001'&&f.versions[0].source.needsSourceValidation)).toBe(true);expect(mappings.some(m=>m.validationStatus==='REFERENCE_REQUIRES_VALIDATION')).toBe(true)})
})
