'use client'
import {useTranslations} from 'next-intl'
import {useLocale} from 'next-intl'
import {Info} from 'lucide-react'
import {getHelp,type HelpTopic} from '@/i18n/help-content'
import type {Locale} from '@/domain/models'
export function PageHeading({titleKey,subtitleKey,namespace}:{titleKey:string;subtitleKey?:string;namespace:string}){const t=useTranslations(namespace);return <div className="page-heading"><div><div className="eyebrow">{namespace.toUpperCase()}</div><h1>{t(titleKey)}</h1>{subtitleKey&&<p>{t(subtitleKey)}</p>}</div></div>}
export function InfoTooltip({messageKey}:{messageKey:string}){const locale=useLocale() as Locale;const copy=getHelp(messageKey as HelpTopic,locale);return <details className="info-popover"><summary aria-label={copy.title}><Info size={13}/></summary><div className="info-panel" role="tooltip"><b>{copy.title}</b><dl><dt>{locale==='de'?'Was ist das?':locale==='tr'?'Nedir?':'What is it?'}</dt><dd>{copy.what}</dd><dt>{locale==='de'?'Warum ist es wichtig?':locale==='tr'?'Neden önemli?':'Why does it matter?'}</dt><dd>{copy.why}</dd><dt>{locale==='de'?'Wie wird es gemessen?':locale==='tr'?'Nasıl ölçülür?':'How is it measured?'}</dt><dd>{copy.measured}</dd><dt>{locale==='de'?'Wie ist es zu interpretieren?':locale==='tr'?'Nasıl yorumlanmalı?':'How should I interpret it?'}</dt><dd>{copy.interpret}</dd></dl></div></details>}
export function EmptyState({children}:{children:React.ReactNode}){return <div className="panel empty-state"><p>{children}</p></div>}
const statusWords:Record<string,[string,string,string]>={PASS:['Pass','Bestanden','Geçti'],FAIL:['Fail','Fehlgeschlagen','Başarısız'],REVIEW:['Review required','Prüfung erforderlich','İnceleme gerekli'],REVIEW_REQUIRED:['Review required','Prüfung erforderlich','İnceleme gerekli'],NOT_TESTED:['Not tested','Nicht getestet','Test edilmedi'],NOT_APPLICABLE:['Not applicable','Nicht anwendbar','Uygulanamaz'],NOT_MAPPED:['Not mapped','Nicht zugeordnet','Eşlenmemiş'],BLOCKED:['Blocked','Gesperrt','Engellendi'],READY:['Ready','Bereit','Hazır'],GRANTED:['Granted','Gewährt','Verildi'],NOT_GRANTED:['Not granted','Nicht gewährt','Verilmedi'],REGRESSION_DETECTED:['Regression detected','Regression erkannt','Regresyon tespit edildi'],NORMAL:['Normal','Normal','Normal'],OPEN:['Open','Offen','Açık'],INVESTIGATING:['Investigating','In Untersuchung','İnceleniyor'],IN_REMEDIATION:['In remediation','In Behebung','Düzeltmede'],READY_FOR_RETEST:['Ready for retest','Bereit für erneuten Test','Yeniden teste hazır'],RESOLVED:['Resolved','Gelöst','Çözüldü'],RISK_ACCEPTED:['Risk accepted','Risiko akzeptiert','Risk kabul edildi'],CRITICAL:['Critical','Kritisch','Kritik'],HIGH:['High','Hoch','Yüksek'],MEDIUM:['Medium','Mittel','Orta'],LOW:['Low','Niedrig','Düşük'],INFORMATIONAL:['Informational','Informativ','Bilgilendirici'],REFERENCE_REQUIRES_VALIDATION:['Source review required','Quellenprüfung erforderlich','Kaynak doğrulaması gerekli'],VALIDATED:['Validated','Validiert','Doğrulandı'],VERIFIED:['Verified','Verifiziert','Doğrulandı'],REVIEWED:['Reviewed','Geprüft','İncelendi'],NEEDS_REVIEW:['Needs review','Prüfung erforderlich','İnceleme gerekli'],STALE:['Stale','Veraltet','Güncelliğini yitirmiş'],PRODUCTION:['Production','Produktion','Üretim'],PILOT:['Pilot','Pilot','Pilot'],STAGING:['Staging','Vorbereitung','Hazırlık']}
export function StatusPill({status}:{status:string}){const locale=useLocale();const words=statusWords[status]??[status.replaceAll('_',' '),status.replaceAll('_',' '),status.replaceAll('_',' ')];const index=locale==='de'?1:locale==='tr'?2:0;return <span className={`pill ${status.toLowerCase().replaceAll('_','-')}`}>{words[index]}</span>}
