'use client'
import {useTranslations} from 'next-intl'
import {PageHeading,StatusPill} from '@/components/assurance/shared'
import {session,roles} from '@/data/demo'
import {workflowRepository} from '@/repositories/workflow'
import {hasPermission} from '@/lib/permissions'
import {useWorkspace} from '@/components/shell/workspace-context'
const permissions=['system:read','system:write','evaluation:run','finding:manage','release:approve','risk:accept','report:export','framework:publish'] as const
export function SettingsPage(){const t=useTranslations();const {organizationId,theme,setTheme}=useWorkspace();return <><PageHeading namespace="settings" titleKey="title" subtitleKey="subtitle"/><div className="settings-grid"><section className="panel"><h2>{t('settings.appearance')}</h2><label>{t('ui.themePreference')}<select value={theme} onChange={e=>setTheme(e.target.value as 'light'|'dark'|'system')}><option value="light">{t('settings.light')}</option><option value="dark">{t('settings.dark')}</option><option value="system">{t('settings.system')}</option></select></label></section><section className="panel"><h2>{t('settings.role')}</h2><p>{session.name} · {t(`roles.${session.role}`)}</p><p>{t('ui.organizationScope')}: {organizationId}</p><div className="permission-list">{permissions.map(p=><p key={p}><StatusPill status={hasPermission(session.role,p)?'GRANTED':'NOT_GRANTED'}/>{t(`permissions.${p}`)}</p>)}</div><p>{t('ui.supportedRoles')}: {roles.map(role=>t(`roles.${role}`)).join(', ')}</p></section><section className="panel"><h2>{t('settings.audit')}</h2>{workflowRepository.auditList().filter(a=>a.organizationId===organizationId).map(a=><p key={a.id}>{a.timestamp} · {a.actor} · {a.action==='Evaluation completed'?t('ui.evaluationCompleted'):a.action==='Release override recorded'?t('ui.auditOverride'):a.action} · {t(`statuses.${a.newState??'ACTIVE'}`)} · {a.objectType} {a.objectId}</p>)}</section></div></>}
