'use client'
import {useTranslations} from 'next-intl'
import {Download,FileText} from 'lucide-react'
import {PageHeading} from '@/components/assurance/shared'
import {useWorkspace} from '@/components/shell/WorkspaceShell'
import {systems,findings,results,frameworks,requirements,mappings,controls,evidence} from '@/data/demo'
import {assuranceScore} from '@/lib/scoring'
import {frameworkCoverage} from '@/lib/coverage'
const types=[['executive','Executive Assurance Report'],['system','System Assurance Assessment'],['technical','Technical Evaluation Report'],['readiness','Compliance Readiness Report'],['finding','Finding Summary'],['gate','Release Gate Report'],['evidence','Evidence Report']]
export function Reports(){const t=useTranslations();const {organizationId}=useWorkspace();const sys=systems.filter(s=>s.organizationId===organizationId);const f=findings.filter(x=>x.organizationId===organizationId);const e=evidence.filter(x=>x.organizationId===organizationId);const r=results.filter(x=>x.evaluationId==='EV-1001'?organizationId==='org-health':x.evaluationId==='EV-2001'?organizationId==='org-bank':false);const score=assuranceScore(r,f);const coverage=frameworks.map(fr=>frameworkCoverage(fr,requirements,mappings,controls,r));const exportJson=(kind:string)=>{const payload={product:'Independent AI Assurance',kind,organizationId,generatedAt:new Date().toISOString(),assuranceScore:score,systems:sys,findings:f,results:r,frameworkCoverage:coverage,evidence:e,disclaimer:t('common.notAdvice')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`iaa-${kind.toLowerCase().replaceAll(' ','-')}.json`;a.click();URL.revokeObjectURL(a.href)};return <><PageHeading namespace="reports" titleKey="title" subtitleKey="subtitle"/><div className="report-grid">{types.map(([key,name])=><section className="panel report-card" key={key}><FileText size={20}/><h2>{t(`reports.${key}`)}</h2><p>{sys.length} systems · {f.length} findings · calculated assurance {score.score}/100.</p><p>JSON preview export only; not a formatted professional report.</p><button className="btn outline" onClick={()=>exportJson(name)}><Download size={14}/>{t('common.export')}</button></section>)}</div><section className="panel report-preview"><h2>{t('reports.executive')}</h2><div className="preview-metrics"><b>{score.score} · assurance</b><b>{f.length} · findings</b><b>{coverage.reduce((n,x)=>n+x.assessedControls,0)} · assessed mappings</b><b>{e.length} · evidence items</b></div><p className="legal-copy">{t('common.notAdvice')}</p></section></>}
